---
- hosts: all
  gather_facts: false
  tasks:
    - name: Setup
      yum: 
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - httpd
          - mariadb
          - mariadb-server
          - php
          - php-common
          - php-mysql
          - php-gd
          - php-xml
          - php-mbstring
          - php-mcrypt
          - php-xmlrpc
          - unzip
          - wget
          - python-pip

    - name: Start htttpd
      service:
         name: httpd
         state: started
         enabled: yes
    - name: Start mariadb
      service:
         name: mariadb
         state: started
         enabled: yes

    - name: Add firewall
      firewalld:
         service: http
         state: enabled
         permanent: yes
         immediate: yes

    - name: Install pymysql
      pip:
        name: pymysql
        state: present

    - name: Set database
      block:
        - name: Set password root
          mysql_user:
             name: root
             password: abc
             login_host: 192.168.52.141
             check_implicit_admin: true
             state: present

        - name: Delete '' user
          mysql_user:
             login_user: root
             login_password: abc
             name: ''
             state: absent

        - name: Copy sql file
          copy: 
            src: ~/sql_commands.sql
            dest: ~/sql_commands.sql

        - name: import sql
          mysql_db:
            state: import
            name: all
            target: ~/sql_commands.sql
            login_user: root
            login_password: abc
      rescue:
        - debug:
            msg: "do already"
    - name: Download wordpress
      get_url: 
         url: https://wordpress.org/wordpress-5.0.tar.gz
         dest: ~/wordpress.tar.gz

    - name: tar wordpress
      unarchive:
         src: ~/wordpress.tar.gz
         dest: /var/www/html/
         remote_src: yes
    - name: set mode
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: apache
        group: apache
        mode: '0755'
    - name: mkdir
      file: 
        path: /var/www/html/wordpress/wp-content/uploads
        state: directory
        group: apache
    - name: mv file
      command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php

    - name: name
      lineinfile:
         path: /var/www/html/wordpress/wp-config.php
         regexp: "define('DB_NAME', 'database_name_here');"
         line: "define('DB_NAME', 'wordpress');"
    - name: username
      lineinfile:
         path: /var/www/html/wordpress/wp-config.php
         regexp: "define('DB_USER', 'username_here');"
         line: "define('DB_USER', 'ansible');"
    - name: password
      lineinfile:
         path: /var/www/html/wordpress/wp-config.php
         regexp: "define('DB_PASSWORD', 'password_here');"
         line: "define('DB_PASSWORD', 'mypassword');"

